# Generated by Django 6.0.6 on 2026-06-30 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('subdominio', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('hora_inicio_jornada', models.TimeField()),
                ('hora_fin_jornada', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('tipo_espacio', models.CharField(choices=[('AULA', 'Aula de Clase Ordinaria'), ('LAB', 'Laboratorio Especializado'), ('AUD', 'Auditorio'), ('SALA', 'Sala de Cómputo')], max_length=10)),
                ('dimensiones_m2', models.FloatField(blank=True, null=True)),
                ('recursos', models.JSONField(blank=True, default=dict)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='proyectos.edificio')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.institucion'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModalidadAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_institucional', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.institucion')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='proyectos.modalidadacademica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MomentoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momentos', to='proyectos.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=255)),
                ('nrc', models.CharField(max_length=20)),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='proyectos.aula')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='proyectos.docente')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.institucion')),
                ('momento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='proyectos.momentoacademico')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.periodoacademico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.institucion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to='proyectos.sede'),
        ),
    ]
