# Generated by Django 6.0.6 on 2026-07-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_clase_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='plano_x',
            field=models.FloatField(blank=True, help_text='Coordenada X en porcentaje respecto al plano', null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='plano_y',
            field=models.FloatField(blank=True, help_text='Coordenada Y en porcentaje respecto al plano', null=True),
        ),
        migrations.AddField(
            model_name='edificio',
            name='plano_evacuacion',
            field=models.ImageField(blank=True, null=True, upload_to='planos/'),
        ),
    ]
