# Generated by Django 6.0.6 on 2026-07-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_aula_plano_x_aula_plano_y_edificio_plano_evacuacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='plano_x',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='plano_y',
        ),
        migrations.RemoveField(
            model_name='edificio',
            name='plano_evacuacion',
        ),
        migrations.AddField(
            model_name='aula',
            name='svg_height',
            field=models.FloatField(blank=True, help_text='Alto SVG', null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='svg_width',
            field=models.FloatField(blank=True, help_text='Ancho SVG', null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='svg_x',
            field=models.FloatField(blank=True, help_text='Posición X en SVG', null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='svg_y',
            field=models.FloatField(blank=True, help_text='Posición Y en SVG', null=True),
        ),
    ]
